object Version {
    const val coreKtx = "1.9.0"
    const val lifecycle = "2.6.2"
    const val androidGradlePlugin = "8.1.1"
    const val kotlin = "1.8.10"
    const val activityCompose = "1.8.0"
    const val googleServices = "4.4.0"
    const val composeBom = "2023.03.00"
    const val junit = "4.13.2"
    const val androidxTestExtJunit = "1.1.5"
    const val espresso = "3.5.1"
    const val firebaseBom = "32.5.0"
    const val materialIconsExtended = "1.5.3"
    const val appcompat = "1.6.1"
    const val material = "1.10.0"
    const val navigationVersion = "2.7.5"
    const val coreSplashscreen = "1.0.0"
    const val daggerHilt = "2.48"
    const val hiltCompiler = "1.1.0"

    const val hiltNavigationCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val okhttp = "4.11.0"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.8.1"

    const val coroutine = "1.7.3"
}